### ISSUE TITLE
ConcurrentModificationException when registering Button in ClickListener

### ISSUE THREAD

**Issue by Hialus** [MrCrayfish/MrCrayfishDeviceMod#17]
When you try to register a button inside a ClickListener the game will crash.

Example Code:
`button.setClickListener(new ClickListener() {
            @Override
            public void onClick(Component component, int i) {
                application.addComponent(new Button(5,5,""));
            }
        });`

Stacktrace:
`java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:206)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:153)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:208)
	at com.mrcrayfish.device.core.Laptop.mouseClicked(Laptop.java:251)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:615)
	at com.mrcrayfish.device.core.Laptop.handleMouseInput(Laptop.java:351)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:580)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1792)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.run(Minecraft.java:407)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)`

**Comment by Itay2805** [comment]
It might have to do something with the fact that the click listener works on a different thread (I think).

**Comment by D-prog-55** [comment]
No. That's because he is modifying the list of Components as it's being looped through. Solution:
1/ Add a list of components in the app (ex: `private ArrayList<Components> toAddNextTick = new ArrayList<Component>();`
2/ Replace the `application.addComponent(new Button(5,5,""));` by `toAddNextTick.add(new Button(5,5,""));`
3/ In _onTick_, check if the list contains things, and if it is, add all the components in the list, then clear it
`if(!toAddNextTick.isEmpty()) {`
`  for(Component c : toAddNextTick) {`
`   this.addComponent(c);`
`  }`
`  toAddNextTick.clear();`
`}`

**Comment by Itay2805** [comment]
well, it is still because of the threading 😛

**Comment by D-prog-55** [comment]
Threading has nothing to do with this. The ClickListener's method is executed in the same thread as the one the buttons are in.

**Comment by Hialus** [comment]
@D-prog-55 Thank you. I got it fixed.
