### ISSUE TITLE
Cut and Paste Onto Flash Drive Crash

### ISSUE THREAD

**Issue by KingYoshiGH** [MrCrayfish/MrCrayfishDeviceMod#44]
How to recreate the crash:
(I was on the test server, and do not know if it happens on singleplayer)

- Cut a file from the file browser (I used a pixel painter file)
- Paste onto flash drive
- Crash

The game will not let me open the crash report, but shows me this.

```
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events
```

**Comment by fabbe50** [comment]
Does not happen on single player.

**Comment by MisterMelDev** [comment]
The full crash log should be in your .minecraft directory, then crash-reports. Please post it here.

**Comment by KingYoshiGH** [comment]
`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/24/17 3:48 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.mrcrayfish.device.programs.system.component.FileBrowser.setClipboardFileToSelected(FileBrowser.java:719)
	at com.mrcrayfish.device.programs.system.component.FileBrowser.lambda$init$4(FileBrowser.java:197)
	at com.mrcrayfish.device.programs.system.component.FileBrowser$$Lambda$175/857679299.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:268)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:216)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:216)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:153)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:205)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:272)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:396)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.device.programs.system.component.FileBrowser.setClipboardFileToSelected(FileBrowser.java:719)
	at com.mrcrayfish.device.programs.system.component.FileBrowser.lambda$init$4(FileBrowser.java:197)
	at com.mrcrayfish.device.programs.system.component.FileBrowser$$Lambda$175/857679299.onClick(Unknown Source)
	at com.mrcrayfish.device.api.app.component.Button.handleMouseClick(Button.java:268)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:216)
	at com.mrcrayfish.device.api.app.Layout.handleMouseClick(Layout.java:216)
	at com.mrcrayfish.device.api.app.Application.handleMouseClick(Application.java:153)
	at com.mrcrayfish.device.core.Window.handleMouseClick(Window.java:205)
	at com.mrcrayfish.device.core.Laptop.func_73864_a(Laptop.java:272)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.mrcrayfish.device.core.Laptop.func_146274_d(Laptop.java:396)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.mrcrayfish.device.core.Laptop

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['KingYoshiMC'/449, l='MpServer', x=337.70, y=46.00, z=-116.92]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (295,64,-186), Chunk: (at 7,4,6 in 18,-12; contains blocks 288,0,-192 to 303,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 82056027 game time, 6001 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityPlayerSP['KingYoshiMC'/449, l='MpServer', x=337.70, y=46.00, z=-116.92], EntityVillager['Merlin'/450, l='MpServer', x=338.50, y=31.00, z=-115.30], EntityItem['item.tile.paper'/466, l='MpServer', x=330.88, y=62.00, z=-145.84], EntityPainting['Painting'/472, l='MpServer', x=326.03, y=67.00, z=-196.00], EntityPainting['Painting'/472, l='MpServer', x=326.03, y=67.00, z=-196.00], EntityPig['Sir Piggles Jr.'/478, l='MpServer', x=347.20, y=65.00, z=-193.69]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 688002664 bytes (656 MB) / 1006632960 bytes (960 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2562 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version      | Source                          | Signature                                |
	|:------ |:----------------- |:------------ |:------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft         | 1.12.2       | minecraft.jar                   | None                                     |
	| UCHIJA | mcp               | 9.42         | minecraft.jar                   | None                                     |
	| UCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.1.2562.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge             | 14.23.1.2562 | forge-1.12.2-14.23.1.2562.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar     | None                                     |
	| UCHIJA | cdm               | 0.2.0-pre6   | device-mod-0.2.0pre6-1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GT 610/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2562
	LWJGL: 2.9.4
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Faithful 1.12.2-rv4.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 3x AMD A6-3500 APU with Radeon(tm) HD Graphics`

**Comment by KingYoshiGH** [comment]
https://pastebin.com/nT6W7XL4

**Comment by MisterMelDev** [comment]
`com.mrcrayfish.device.programs.system.component.FileBrowser.setClipboardFileToSelected(FileBrowser.java:719)` is where the error occurs. Either the file is null or `file.isProtected()` returns null.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/MrCrayfishDeviceMod/commit/aa6a50975673795ed53b05616386d529aa88e70a
