### ISSUE TITLE
Game Crash with Laptops

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishDeviceMod#52]
I have no idea what went wrong so I'll post the log!

https://pastebin.com/JXw6Haks

**Comment by MisterMelDev** [comment]
Important parts of the stacktrace:
`Caused by: java.lang.NullPointerException
    at com.mrcrayfish.device.api.print.PrintingManager.getPrintIdentifier(PrintingManager.java:87) ~[PrintingManager.class:?]
    at com.mrcrayfish.device.api.print.IPrint.writeToTag(IPrint.java:46) ~[IPrint.class:?]
    at com.mrcrayfish.device.api.print.IPrint.generateItem(IPrint.java:66) ~[IPrint.class:?]
    at com.mrcrayfish.device.block.BlockPaper.breakBlock(BlockPaper.java:110) ~[BlockPaper.class:?]
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:615) ~[Chunk.class:?]
    at net.minecraft.world.World.setBlockState(World.java:400) ~[World.class:?]
    at net.minecraft.block.Block.removedByPlayer(Block.java:1422) ~[Block.class:?]`
`Caused by: java.lang.NullPointerException
    at com.mrcrayfish.device.tileentity.TileEntityDevice.receiveBeacon(TileEntityDevice.java:91) ~[TileEntityDevice.class:?]
    at com.mrcrayfish.device.core.network.Router.sendBeacon(Router.java:141) ~[Router.class:?]
    at com.mrcrayfish.device.core.network.Router.update(Router.java:40) ~[Router.class:?]
    at com.mrcrayfish.device.tileentity.TileEntityRouter.update(TileEntityRouter.java:39) ~[TileEntityRouter.class:?]
    at net.minecraft.world.World.updateEntities(World.java:2004) ~[World.class:?]
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:642) ~[WorldServer.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840) ~[MinecraftServer.class:?]`
