### ISSUE TITLE
I get this when trying to run Minecraft with device-api-0.2.0-1.12.2.jar

### ISSUE THREAD

**Issue by banana439monkey** [MrCrayfish/MrCrayfishDeviceMod#66]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/14/18 10:35 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.mrcrayfish.device.init.RegistrationHandler$Blocks.register(RegistrationHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_Blocks_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.device.init.RegistrationHandler$Blocks.register(RegistrationHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_Blocks_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 103545688 bytes (98 MB) / 346337280 bytes (330 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2589 Optifine OptiFine_1.12.2_HD_U_C8 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                 | Signature                                |
	|:----- |:-------------------- |:------------ |:-------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2       | minecraft.jar                          | None                                     |
	| UCH   | mcp                  | 9.42         | minecraft.jar                          | None                                     |
	| UCH   | FML                  | 8.0.99.99    | forge-1.12.2-14.23.1.2589.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.1.2589 | forge-1.12.2-14.23.1.2589.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater    | 1.0          | MercuriusUpdater-1.12.2.jar            | None                                     |
	| UCH   | securitycraft        | v1.8.3       | [1.12.x] SecurityCraft v1.8.3.jar      | None                                     |
	| UCH   | cyclopscore          | 0.11.0       | CyclopsCore-1.12.2-0.11.0.jar          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | colossalchests       | 1.6.7        | ColossalChests-1.12-1.6.7.jar          | None                                     |
	| UCH   | cookingforblockheads | 6.3.17       | CookingForBlockheads_1.12.1-6.3.17.jar | None                                     |
	| UCE   | cdm                  | 0.2.0        | device-api-0.2.0-1.12.2.jar            | None                                     |
	| UCH   | cfm                  | 4.1.5        | furniture-4.1.5-1.12.2.jar             | None                                     |
	| UCH   | landlust             | 1.12.2-0.3.5 | landlust-1.12.2-0.3.5.jar              | None                                     |
	| UCH   | personalcars         | 1.4          | PersonalCars-1.4.jar                   | None                                     |
	| UCH   | worldedit            | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 2500'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2589
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 2500 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Custom_Record_Sounds, CodeCrafted Custom - 1.11+.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.166 High.zip
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 2500
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by JacksonPlayz** [comment]
First of all, put your logs in pastebin.
Second of all, you have to use the device-api in a development workspace, you can't use it with normal Forge instance

**Comment by banana439monkey** [comment]
1. Sorry 'bout that
2. Ohh.

**Comment by MrCrayfish** [comment]
Download the normal version here: https://minecraft.curseforge.com/projects/mrcrayfishs-device-mod
